version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "is-online"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2ehqqh9o6nan"
s3_prefix = "is-online"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
