overrides:
  chokidar: 4.0.0
  '@esbuild-kit/core-utils>esbuild': 0.27.3
  hono: 4.12.7
  '@hono/node-server': 1.19.11
  immutable: 5.1.5
  koa: 3.1.2
  'ng-morph>minimatch': 10.2.4
  'http-proxy-agent>@tootallnate/once': 3.0.1
  'postcss-url>minimatch': 3.1.4
  serialize-javascript: 7.0.3
  svgo: 3.3.3
  tar: 7.5.11
  typescript: 5.9.2

onlyBuiltDependencies:
  - puppeteer
