import {
  PUPPETEER_REPLAY_CUSTOM_STEP_TYPE,
  PUPPETEER_REPLAY_ASSERTION_STEP_TYPE,
  PUPPETEER_REPLAY_USER_STEP_TYPE,
} from './puppeteer-replay/puppeteer-replay-step-type';

export const STEP_TYPE = {
  CUSTOM_STEP: PUPPETEER_REPLAY_CUSTOM_STEP_TYPE.CUSTOM_STEP,
  ...PUPPETEER_REPLAY_ASSERTION_STEP_TYPE,
  ...PUPPETEER_REPLAY_USER_STEP_TYPE,
} as const;
export type StepType = (typeof STEP_TYPE)[keyof typeof STEP_TYPE];
