name: CI

env:
  NODE_VERSION: 24.14.0
  is-main-branch: ${{ github.ref == 'refs/heads/main' }}
  is-pull-request: ${{ github.event_name == 'pull_request' }}

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  setup:
    name: Setup CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
      # Derive appropriate SHAs for base and head for `nx affected` commands
      - uses: nrwl/nx-set-shas@v3
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      # Aggressive NPM dependency caching
      # https://dev.to/drakulavich/aggressive-dependency-caching-in-github-actions-3c64
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        id: cache-primes
        with:
          path: |
            node_modules
            ~/.cache
            dist
          key: &npm_cache_key ${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('package-lock.json') }}

      - name: Clean Install Dependencies
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: npm ci

  lint:
    name: Lint Affected
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
      # Derive appropriate SHAs for base and head for `nx affected` commands
      - uses: nrwl/nx-set-shas@v3
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Cache NPM Dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache
            dist
          key: *npm_cache_key

      - name: Lint Affected
        run: npx nx affected --target=lint --parallel=3

  test:
    name: Test Affected
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
      # Derive appropriate SHAs for base and head for `nx affected` commands
      - uses: nrwl/nx-set-shas@v3
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Cache NPM Dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache
            dist
          key: *npm_cache_key

      - name: Test Affected
        run: npx nx affected --target=test --parallel=3

  build:
    name: Build Affected
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
      # Derive appropriate SHAs for base and head for `nx affected` commands
      - uses: nrwl/nx-set-shas@v3
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Cache NPM Dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache
            dist
          key: *npm_cache_key

      - name: Build Affected
        run: npx nx affected -t build build-storybook --parallel=3

#  e2e:
#    name: E2E Affected
#    needs: [build]
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#      - uses: nrwl/nx-set-shas@v3
#      - uses: actions/setup-node@v4
#        with:
#          node-version: ${{ env.NODE_VERSION }}
#          cache: 'npm'
#
#      - name: Cache NPM Dependencies
#        uses: actions/cache@v4
#        with:
#          path: |
#            node_modules
#            ~/.cache
#            dist
#          key: *npm_cache_key
#
#      - name: E2E Affected
#        run: npx nx affected --target=e2e --parallel=3

#  publish-storybook:
#    name: Publish Storybook
#    needs: [build, lint]
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#      - uses: nrwl/nx-set-shas@v3
#      - uses: actions/setup-node@v4
#        with:
#          node-version: ${{ env.NODE_VERSION }}
#          cache: 'npm'
#
#      - name: Cache NPM Dependencies
#        uses: actions/cache@v4
#        with:
#          path: |
#            node_modules
#            ~/.cache
#            dist
#          key: *npm_cache_key
#
#      - name: Publish Storybook Affected
#        run: npx nx affected --target=publish-storybook --parallel=3 --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }}
