name: Markets CI

env:
  NODE_VERSION: 18
  is-main-branch: ${{ github.ref == 'refs/heads/main' }}
  is-pull-request: ${{ github.event_name == 'pull_request' }}

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run test

#  deploy-server:
#    name: Deploy Server
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - uses: actions/setup-node@v3
#        with:
#          node-version: ${{ env.NODE_VERSION }}
#          cache: npm
#
#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: eu-central-1
#
#      - name: Install dependencies
#        run: npm install
#
#      - name: Build Dev
#        run: npm run build
#
#      - name: Deploy Dev Server
#        if: ${{ env.is-pull-request == 'true' }}
#        run: npm run deploy:runner
#
#      - name: Deploy Prod Server
#        if: ${{ env.is-main-branch == 'true' }}
#        run: npm run deploy:runner

  deploy-client:
    name: Deploy Client
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Install dependencies
        run: npm install

      - name: Build Dev
        run: npm run build

      - name: Deploy Dev Client
        if: ${{ env.is-pull-request == 'true' }}
        run: npm run deploy:dev

      - name: Deploy Prod Client
        if: ${{ env.is-main-branch == 'true' }}
        run: npm run deploy:prod
