name: App Speed CI Pipeline

env:
  NODE_VERSION: '18'
  is-main-branch: ${{ github.ref == 'refs/heads/main' }}
  is-pull-request: ${{ github.event_name == 'pull_request' }}

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  setup:
    uses: ./.github/workflows/setup-cache.yml@main
    with:
      node-version: ${{ env.NODE_VERSION }}

  lint:
    name: Lint Affected
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Lint Affected
        run: npx nx affected --target=lint --parallel=3

  test:
    name: Test Affected
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Test Affected
        run: npx nx affected --target=test --parallel=3

  build:
    name: Build Affected
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Build Affected
        run: npx nx affected --target=build --parallel=3

  deploy-front-end:
    name: Deploy Front-End
    needs: [build, lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Deploy Dev Client
        if: ${{ env.is-pull-request == 'true' }}
        run: npx nx affected --target=deploy --exclude='*,!tag:frontend' --environment=dev
      - name: Deploy Prod Client
        if: ${{ env.is-main-branch == 'true' }}
        run: npx nx affected --target=deploy --exclude='*,!tag:frontend' --environment=prod

  deploy-server:
    name: Deploy Server
    needs: [build, lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Deploy Dev Server
        if: ${{ env.is-pull-request == 'true' }}
        run: npx nx affected --target=deploy --exclude='*,!tag:backend' --environment=dev
      - name: Deploy Prod Server
        if: ${{ env.is-main-branch == 'true' }}
        run: npx nx affected --target=deploy --exclude='*,!tag:backend' --environment=prod
