name: Deploy Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment environment
        required: true
        type: choice
        options:
          - development
          - production
        default: development

env:
  NODE_VERSION: 24.14.0
  PNPM_VERSION: 10.11.0

jobs:
  deploy-frontend:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy Frontend (Auto Main)
        if: ${{ github.event_name == 'push' }}
        run: pnpm exec nx deploy portal --configuration=production

      - name: Deploy Frontend (Manual)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          DEPLOY_ENV: ${{ github.event.inputs.environment }}
        run: pnpm exec nx deploy portal --configuration="${DEPLOY_ENV}"
