name: RELEASE
on: [workflow_dispatch]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Cache NPM dependencies
        uses: actions/cache@v4
        id: cache-primes
        with:
          path: |
            node_modules
            ~/.cache
            dist
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Clean Install Dependencies
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: npm ci
#      - name: Lint
#        run: npx nx run-many -t lint
#      - name: Test
#        run: npx nx run-many -t test --configuration=ci
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
